export const REGISTER = "/users/register/"
export const LOGIN = "/users/login/"
export const GOOGLE_LOGIN = "/users/rest-auth/google/"
export const APPLE_LOGIN = "/users/rest-auth/apple/"
export const FACEBOOK_LOGIN = "/users/rest-auth/facebook/"
export const FORGOT_PASSWORD = "/users/reset_password_sent_email/"
export const NEW_PASSWORD = "/users/reset_password/"
export const TOKEN = "@Token"
